### ISSUE TITLE
AD: We want artifactory-cleanup-rules!

### ISSUE THREAD

**Issue by allburov** [devopshq/artifactory-du#2]
copy-past from [README.md#ad](https://github.com/devopshq/artifactory-du#ad)
-----
We also have python-script for Artifactory intelligence cleanup rules with config format like this:
```python
GOOD_FILTER_PATH_SYMBOLS = [
    r'*release*', r'*/r-*',
    r'*master*',
    r'*stable*',
]

RULES = [
    {'name': 'Clean all *.tmp',
     'rules': [
         rules.repo_by_mask('*.tmp'),
         rules.delete_older_than_n_days(7),
     ]},

    {'name': 'Clean all *.BANNED after 7 days',
     'rules': [
         rules.repo_by_mask('*.BANNED'),
         rules.delete_older_than_n_days(7),
     ]},

    {'name': 'Clean all *.snapshot after 30 days',
     'rules': [
         rules.repo_by_mask('*.snapshot'),
         rules.delete_older_than_n_days(30),
     ]},

     {'name': 'tech-symbols',
     'rules': [
         rules.repo, # repo-name like 'name'
         rules.delete_older_than_n_days(30),
         rules.filter_without_path_mask(GOOD_FILTER_PATH_SYMBOLS),
         rules.filter_without_filename_mask(GOOD_FILTER_PATH_SYMBOLS),
         rules.filter_by_filename_mask('*-*symbols.tar.gz'),
         rules.without_downloads()
     ]},

     {'name': 'docker-scmdev',
     'rules': [
         rules.repo, # repo-name like 'name'
         rules.filter_by_path_mask('scmdev.test*'),
         rules.delete_images_older_than_n_days(1),
     ]},
]

```

If you want it, please vote for issue and we will schedule time for move project to open-source: https://github.com/devopshq/artifactory-du/issues/2

**Comment by rtulke** [comment]
please commit your clean-up script :)

**Comment by pvdissel** [comment]
Note that there are also a bunch of cleanup plugins available at:
https://github.com/jfrog/artifactory-user-plugins/tree/master/cleanup
And https://github.com/jfrog/artifactory-user-plugins/tree/master/archive/archiveOldArtifacts

I found https://github.com/jfrog/artifactory-user-plugins/tree/master/archive/archiveOldArtifacts to be most useful, I extended it to also support moving the artifacts disk, this way you can really "archive" old artifacts to another disk instead of just deleting them. I will submit these changes to the repo above soon. But already cleaned/archived about 7TB of artifacts using this plugin

**Comment by casz** [comment]
I'd very much appreciate this rule based approach!

**Comment by nikolasj** [comment]
We are going to move the project to open source in the next 2 weeks

**Comment by nikolasj** [comment]
We created `artifactory-cleanup` [project](https://github.com/devopshq/artifactory-cleanup).
You can try to use.
To do this you need install package and follow [instration](https://github.com/devopshq/artifactory-cleanup/blob/master/README.md#usage):
`python3 -mpip install  git+https://github.com/devopshq/artifactory-cleanup.git`. 
We'll add pypi later.

**Comment by casz** [comment]
MANY THANKS @nikolasj

**Comment by allburov** [comment]
Fixed, thank you all!
